server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          # Reemplazar valores por defecto o pasarlos por variables de entorno
          issuer-uri: https://cognito-idp.${AWS_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID:us-east-1_xxxxxxxxx}

cognito:
  # App Client ID configurado en tu User Pool
  client-id: ${COGNITO_CLIENT_ID:xxxxxxxxxxxxxxxxxxxxxxxxxx}

services:
  orders:
    url: ${ORDERS_SERVICE_URL:http://localhost:8081}
  catalog:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}